
package Vista_fight;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class fight_or_die extends javax.swing.JFrame {
    
    protected String usuario;
    protected String contrasena;

    public String getContrasena() {
        return contrasena;
    }

    public JPasswordField getUser_Pass() {
        return User_Pass;
    }

    public JTextField getUser_nick() {
        return User_nick;
    }
    
    
    /**
     * Creates new form fight_or_die
     */
    public fight_or_die() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**Asignar icino en a la interfaz**/
    public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_nick = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        User_Pass = new javax.swing.JPasswordField();
        jInicio_Sesion = new javax.swing.JButton();
        jRegistro = new javax.swing.JButton();
        password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User_nick.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        User_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_nickActionPerformed(evt);
            }
        });
        getContentPane().add(User_nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 100, 30));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel1.setText("Bienvenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        Salir.setBackground(new java.awt.Color(197, 0, 0));
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        User_Pass.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        User_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_PassActionPerformed(evt);
            }
        });
        getContentPane().add(User_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 100, 30));

        jInicio_Sesion.setText("Inisiar sesión");
        jInicio_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInicio_SesionActionPerformed(evt);
            }
        });
        getContentPane().add(jInicio_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jRegistro.setText("Registrarme");
        jRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(jRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio (1)_1.jpg"))); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void User_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_nickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_nickActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void User_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_PassActionPerformed

    private void jInicio_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInicio_SesionActionPerformed
        usuario = User_nick.getText();
        char [] password = User_Pass.getPassword();
        for(int i=0; i<password.length; i++){
            contrasena+=password[i];
            
        }
        System.out.println(contrasena);
        
        
        
    }//GEN-LAST:event_jInicio_SesionActionPerformed

    private void jRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistroActionPerformed
        Formulario registrar = new Formulario();/*Crear objeto*/
        registrar.setVisible(true);/**Hacer visible la ventana**/
        this.dispose();/**Cerrar ventana de sobra**/
    }//GEN-LAST:event_jRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fight_or_die.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fight_or_die.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fight_or_die.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fight_or_die.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fight_or_die().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JPasswordField User_Pass;
    private javax.swing.JTextField User_nick;
    private javax.swing.JButton jInicio_Sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jRegistro;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
}
