/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_fight;

/**
 *
 * @author usuario
 */
public class Formulario extends javax.swing.JFrame {
    public String nombre, apellido, nickname, correo, password, edad;
    
    
    /*constructor*/
    public Formulario(String nombre, String apellido, String nickname, String correo, String password, String edad) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.nickname = nickname;
        this.correo = correo;
        this.password = password;
        this.edad = edad;
    }

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    Formulario(String nombre, String apellido, int edad, String correo, String nickname, String password) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSend_Form = new javax.swing.JButton();
        jReturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        T_apellido = new javax.swing.JTextField();
        T_edad = new javax.swing.JTextField();
        T_nickname = new javax.swing.JTextField();
        T_correo = new javax.swing.JTextField();
        T_nombre = new javax.swing.JTextField();
        T_password = new javax.swing.JPasswordField();
        jFondo_Registro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btnSend_Form.setBackground(new java.awt.Color(255, 0, 0));
        btnSend_Form.setForeground(new java.awt.Color(255, 255, 255));
        btnSend_Form.setText("Enviar");
        btnSend_Form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSend_FormActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend_Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jReturn.setBackground(new java.awt.Color(255, 0, 0));
        jReturn.setForeground(new java.awt.Color(255, 255, 255));
        jReturn.setText("Cancelar");
        jReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnActionPerformed(evt);
            }
        });
        getContentPane().add(jReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nick-Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Aceptar terminos & condiciones");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 30, 30));

        T_apellido.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(T_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, -1));

        T_edad.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        T_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_edadActionPerformed(evt);
            }
        });
        getContentPane().add(T_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        T_nickname.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(T_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, -1));

        T_correo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(T_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 90, -1));

        T_nombre.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(T_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        T_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(T_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, -1));

        jFondo_Registro.setForeground(new java.awt.Color(255, 255, 255));
        jFondo_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Puntuación (1).jpg"))); // NOI18N
        jFondo_Registro.setText("d");
        jFondo_Registro.setToolTipText("dad");
        getContentPane().add(jFondo_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSend_FormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSend_FormActionPerformed
        nombre = T_nombre.getText();
        apellido = T_apellido.getText();
        edad = T_edad.getText();
        /*String cambio = T_edad.getText();
        edad = Integer.parseInt(cambio);*/
        nickname = T_nickname.getText();
        correo = T_correo.getText();
        password = T_password.getText();
        /*almacenar datos
        datos_User ejecucion = new datos_User();
        ejecucion.guardar_valor(nombre, apellido, edad, correo, nickname, password);*/
        /*Reseteo de labes*/
        
    }//GEN-LAST:event_btnSend_FormActionPerformed

    @Override
    public String toString() {
        return "Formulario{"+nombre+ apellido+ edad + correo+ nickname+ password;
    }

    public String getNombre() {
        return nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public String getNickname() {
        return nickname;
    }

    public String getCorreo() {
        return correo;
    }

    public String getPassword() {
        return password;
    }

    public String getEdad() {
        return edad;
    }



    private void jReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnActionPerformed
        fight_or_die registrar = new fight_or_die();/*Crear objeto*/
        registrar.setVisible(true);/**Hacer visible la ventana**/
        this.dispose();/**Cerrar ventana de sobra**/
    }//GEN-LAST:event_jReturnActionPerformed

    private void T_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_passwordActionPerformed

    private void T_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_edadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField T_apellido;
    public javax.swing.JTextField T_correo;
    public javax.swing.JTextField T_edad;
    public javax.swing.JTextField T_nickname;
    public javax.swing.JTextField T_nombre;
    public javax.swing.JPasswordField T_password;
    public javax.swing.JButton btnSend_Form;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jFondo_Registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jReturn;
    // End of variables declaration//GEN-END:variables
}
